version: "3"

services:
    app:
        build: ./
        volumes:
        - ./app:/app
        ports:
        - '5000:5000'
        working_dir: /app
        command: python3 app.py
        # depends_on:
        # -    db
        restart: unless-stopped

    # db:
    #     image: jamielsharief/mysql:latest
    #     volumes:
    #     - .db-data:/var/lib/mysql
    #     environment:
    #     - MYSQL_ROOT_PASSWORD=root
    #     ports:
    #     - "3306:3306"

    # redis:
    #     image: redis

    nginx:
        image: nginx
        ports:
        - "443:443"
        - "80:80"
        volumes:
        - ./nginx/config/:/etc/nginx/conf.d/
        - ./app:/app
        depends_on:
        -    app

networks:
    default:
        
        


